import mongoose from 'mongoose';

const materialSchema = mongoose.Schema({
  classroom: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'Classroom',
  },
  user: { // The teacher who uploaded it
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'User',
  },
  fileName: { // The name generated by multer
    type: String,
    required: true,
  },
  originalName: { // The original name of the file
    type: String,
    required: true,
  },
  filePath: { // The path on the server
    type: String,
    required: true,
  },
}, { timestamps: true });

const Material = mongoose.model('Material', materialSchema);
export default Material;